name: Murraytest
favicon: null
layout_spectrum: 0.669620011234656
typography_spectrum: 0.13141460018232465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.13889934355393052
  lightness: 0.030767826829105616
  saturation: 0.00825326843187213
  rhythmicContrast: 0.8764256874565035
purpose: []
